notifications:
  email: false

rvm:
  - 2.2.2

notifications:
  irc: "irc.freenode.org#blacklight"

env:
  global:
    - JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby


script:
  - bundle exec rake
  - bundle exec rake rubocop
