addons:
  chrome: stable
notifications:
  email: false

rvm:
  - 2.4.3

matrix:
  include:
    - rvm: 2.3.6
      env: "RAILS_VERSION=5.0.6"

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

notifications:
  irc: "irc.freenode.org#blacklight"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RAILS_VERSION=5.1.5

sudo: false
language: ruby

script:
  - bundle exec rake

jdk: oraclejdk8

cache:
  ##
  # Caching bundler here in a hope to reduce Travis test time
  bundler: true
  ##
  # We don't really know how this will work, but lets see.
  directories:
    - .internal_test_app/tmp/cache/assets/sprockets
